-- Tables
CREATE TABLE IF NOT EXISTS Users(
    userId INT PRIMARY KEY AUTO_INCREMENT(1000, 1000),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS UserDevice(
    userId INT NOT NULL,
    deviceHash VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS UserToken(
    userId INT NOT NULL,
    token VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS UserBankCard(
    userId INT NOT NULL,
    cardId VARCHAR(100) PRIMARY KEY NOT NULL,
    cardNumber VARCHAR(100) NOT NULL,
    cvc INT NOT NULL,
    name VARCHAR(100),
    amount DECIMAL(10,2) DEFAULT 0,
    currency VARCHAR(100) DEFAULT 'HUF'
);

-- Sequences
CREATE SEQUENCE card_id_seq START WITH 1 INCREMENT BY 1;